inputdata <- read.csv("./household_power_consumption.txt", header=T, sep=';', na.strings="?", nrows=2075259, check.names=F, stringsAsFactors=F, comment.char="", quote='\"')
inputdata$Date <- as.Date(inputdata$Date, format="%d/%m/%Y")
subsetData <- subset(inputdata, subset=(Date >= "2007-02-01" & Date <= "2007-02-02"))
rm(inputdata)
datetime <- paste(as.Date(subsetData$Date), subsetData$Time)
subsetData$Datetime <- as.POSIXct(datetime)
hist(subsetData$Global_active_power, main="Global Active Power", xlab="Global Active Power (kilowatts)", ylab="Frequency", col="Red")
dev.copy(png, file="plot1.png", height=480, width=480)
dev.off()
